reserveren/config/routes.rb
Reserveren::Application.routes.draw do
<<<<<<< HEAD
  root to: 'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'
 match '/reserveren', to: 'static_pages#reserveren', via: 'get'
 match '/contact', to: 'static_pages#contact', via: 'get'
match '/menu', to: 'static_pages#menu', via: 'get'

match '/reserveren/stap1', to: 'static_pages#stap1', via: 'get'
match '/reserveren/stap2', to: 'static_pages#stap2', via: 'get' 
match '/reserveren/stap3', to: 'static_pages#stap3', via: 'get'
=======
  resources :reservations

  resources :tables

  resources :users

>>>>>>> c71c113946d26f902b500fcfb6eff1a20af17014

end

reserveren/app/models/reservation.rb
class Reservation < ActiveRecord::Base
end

reserveren/app/models/table.rb
class Table < ActiveRecord::Base
end

reserveren/app/models/user.rb
class User < ActiveRecord::Base
validates :phone, length: { maximum: 12, minimum: 10}
end

reserveren/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

reserveren/app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @reservation }
      else
        format.html { render action: 'new' }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:table, :user, :date)
    end
end

reserveren/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def reserveren
  end
  
   def contact
  end
  
  def menukaart
  end
  
  def stap1
  end
  
  def stap2
  end
  
  def stap3
  end
  
end

reserveren/app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :set_table, only: [:show, :edit, :update, :destroy]

  # GET /tables
  # GET /tables.json
  def index
    @tables = Table.all
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
  end

  # GET /tables/new
  def new
    @table = Table.new
  end

  # GET /tables/1/edit
  def edit
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(table_params)

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render action: 'show', status: :created, location: @table }
      else
        format.html { render action: 'new' }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tables/1
  # PATCH/PUT /tables/1.json
  def update
    respond_to do |format|
      if @table.update(table_params)
        format.html { redirect_to @table, notice: 'Table was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table.destroy
    respond_to do |format|
      format.html { redirect_to tables_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @table = Table.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def table_params
      params.require(:table).permit(:Seats)
    end
end

reserveren/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :phone)
    end
end

reserveren/app/helpers/application_helper.rb
module ApplicationHelper
end

reserveren/app/helpers/reservations_helper.rb
module ReservationsHelper
end

reserveren/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

reserveren/app/helpers/tables_helper.rb
module TablesHelper
end

reserveren/app/helpers/users_helper.rb
module UsersHelper
end

reserveren/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ni So Lekkel | <%= @title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</body>
</html>

reserveren/app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :table %><br>
    <%= f.number_field :table %>
  </div>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.number_field :user %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

reserveren/app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

reserveren/app/views/reservations/index.html.erb
<h1>Listing reservations</h1>

<table>
  <thead>
    <tr>
      <th>Table</th>
      <th>User</th>
      <th>Date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.table %></td>
        <td><%= reservation.user %></td>
        <td><%= reservation.date %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

reserveren/app/views/reservations/new.html.erb
<h1>New reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

reserveren/app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Table:</strong>
  <%= @reservation.table %>
</p>

<p>
  <strong>User:</strong>
  <%= @reservation.user %>
</p>

<p>
  <strong>Date:</strong>
  <%= @reservation.date %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>

reserveren/app/views/static_pages/contact.html.erb
<% @title="Contact" %>
<h1>Contact</h1>
<p>Pim is gek tralalalalalalalalalalalalala hahaha goh</p>

reserveren/app/views/static_pages/help.html.erb
<% @title="Help" %>
<h1>Help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

reserveren/app/views/static_pages/home.html.erb
<% @title="Home" %>
<h1>Home</h1>
<p>This is the home page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

reserveren/app/views/static_pages/menu.html.erb
<% @title="Menukaart" %>
<h1>Menukaart</h1>
<p>Lekkel eten hool sambar bij</p>

reserveren/app/views/static_pages/reserveren.html.erb
<% @title="Reserveren" %>
<h1>Reserveren</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

reserveren/app/views/static_pages/stap1.html.erb
<% @title="Stap 1" %>
<h1>Reserveringswensen</h1>
<p>
  Op deze pagina kiest u een datum en tijd en de tafel die u op deze datum wil reserveren. Indien u meerdere tafels wilt reserveren voor grote groepen kunt u een reservering telefonisch doorgeven.
</p>

reserveren/app/views/static_pages/stap2.html.erb
<% @title="Stap 2" %>
<h1>Contactgegevens</h1>
<p>
  Vul op deze pagina uw contactgegevens in. Indien u uw emailadres invult ontvangt u per mail een bevestiging van de reservering.
</p>

reserveren/app/views/static_pages/stap3.html.erb
<% @title="Stap 3" %>
<h1>Bevestig uw reservering</h1>
<p>
  Controleer uw reservering en klik op bevestigen om uw reservering af te ronden.
</p>

reserveren/app/views/tables/_form.html.erb
<%= form_for(@table) do |f| %>
  <% if @table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@table.errors.count, "error") %> prohibited this table from being saved:</h2>

      <ul>
      <% @table.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Seats %><br>
    <%= f.number_field :Seats %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

reserveren/app/views/tables/edit.html.erb
<h1>Editing table</h1>

<%= render 'form' %>

<%= link_to 'Show', @table %> |
<%= link_to 'Back', tables_path %>

reserveren/app/views/tables/index.html.erb
<h1>Listing tables</h1>

<table>
  <thead>
    <tr>
      <th>Seats</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tables.each do |table| %>
      <tr>
        <td><%= table.Seats %></td>
        <td><%= link_to 'Show', table %></td>
        <td><%= link_to 'Edit', edit_table_path(table) %></td>
        <td><%= link_to 'Destroy', table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Table', new_table_path %>

reserveren/app/views/tables/new.html.erb
<h1>New table</h1>

<%= render 'form' %>

<%= link_to 'Back', tables_path %>

reserveren/app/views/tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Seats:</strong>
  <%= @table.Seats %>
</p>

<%= link_to 'Edit', edit_table_path(@table) %> |
<%= link_to 'Back', tables_path %>

reserveren/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

reserveren/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

reserveren/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

reserveren/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

reserveren/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>